### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by ar4mro** [ympons/flasher#1]
Hi ympons, I've had problems with jwasham app and I'm now trying your version. Yet, when I type the command 'PORT=5800 $GOPATH/bin/flasher' it returns the message "Unable to connect to the DB: unable to open database file".

I haven't used Go before, I would really appreciate your help, thanks in advance.

**Comment by ympons** [comment]
Hi @alv2r, I updated the README file. The easy way is to run the command from the flasher folder for using the jwasham db.
```
cd $GOPATH/src/github.com/ympons/flasher
PORT=5800 $GOPATH/bin/flasher
```
If you want to provide your own uri for the db you can pass it through the `DATABASE_URL` env variable:
```
DATABASE_URL=$GOPATH/src/github.com/ympons/flasher/db/cards-jwasham.db PORT=5800 $GOPATH/bin/flasher
```

Cheers!
